### PR TITLE
Can now delete resources and refer to settings as variables

### PR DESCRIPTION
**Pull request by lewismarshall**
See issues #24 and #25 for details.

### CODE REVIEW

**Comment by lewismarshall** [comment]
@jon-shanks @PurpleBooth @gambol99

**Comment by lewismarshall** [comment]
Be good to get a LGTM for this one @allandegnan @jon-shanks

**Comment by allandegnan** [comment]
LGTM

**Comment by PurpleBooth** [comment]
LGTM

**Pull request merged**
